### ISSUE TITLE
Navigation Funkiness

### ISSUE THREAD

**Issue by illuminate3** [frandiox/vue-onsenui-kitchensink#1]
I noticed that if you click on a link from the home page you get back arrows and no left slide in menu. If you use the slide in menu or the bottom tabs you don't get the back arrow.

Also, When in safari the I don't see the green material fallback but in Chrome I get the full material experience. How can I just restrict it to look like one or the other?

thanks for the repo! I'm using this to learn vue, onsen ui, monaca all at the same time.

**Comment by frandiox** [comment]
@illuminate3 The navigation is made like that on purpose. Links in Home are pushing pages to the stack (in VOnsNavigator component)  and hiding the menu. The other links (the ones in the tabbar or the menu) are separating different sections in the app. It is made in this way just to show different examples, in a real app you can choose to only push pages with animations if you want.

About the styles, the default one is iOS flat design but it displays material when the platform is Android. You can disable these changes with `$ons.disableAutoStyling()`. If you always want material design, you can either manually set `modifier="material"` for every component or fake the platform with `$ons.platform.select('android')`. Everything is basically optional.

This is a bit experimental but you can try for testing:

https://frandiox.github.io/vue-onsenui-kitchensink/?platform=ios
https://frandiox.github.io/vue-onsenui-kitchensink/?platform=android

Otherwise, in Chrome developer tools you can choose Nexus or iPhone devices. It changes the style as well.

Hope this clarifies something!
